repos:
  - repo: "https://github.com/astral-sh/uv-pre-commit"
    rev: 0.9.7
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests/
        files: ^(tests/.*\.py|src/close_mongo_ops_manager/.*\.py)$
        language: system
        pass_filenames: false
